# Generated by Django 5.0.7 on 2024-07-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
