# Generated by Django 5.0.7 on 2024-07-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_category_options_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='anwser',
            new_name='answer',
        ),
    ]
