# Generated by Django 5.0.7 on 2024-07-16 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('course', '0010_lesson_video_id_alter_lesson_lesson_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acticity',
            new_name='Activity',
        ),
    ]
